FROM ubuntu:focal

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libtinfo5
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang-10
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libxml2
